apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8082   # Spring Boot listens on 8082
      nodePort: 30080    # External port




